version: '3.8'

services: 
  php-fpm:
    build:
      context: php-fpm
      dockerfile: Dockerfile
      target: php
      args:
        # See all tags here https://github.com/docker-library/docs/blob/master/php/README.md#supported-tags-and-respective-dockerfile-links
        VARIANT: "7.2-fpm"

    volumes:
      - ../:/app:cached

    # Runs app on the same network as the nginx container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:nginx

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        VARIANT: "latest"
    restart: unless-stopped
    volumes:
      - ../:/app

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    # Runs app on the same network as the nginx container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:nginx
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
volumes:
  mariadb-data:
