version: '3.8'

services: 
  php-fpm:
    image: php:8.3-fpm

    volumes:
      - ../app:/var/www/html:cached

    # Runs app on the same network as the nginx container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:nginx

    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./php-fpm.conf:/etc/nginx/conf.d/default.conf
      - ../app:/var/www/html

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    # Runs app on the same network as the nginx container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:nginx
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb


    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
volumes:
  mariadb-data:
